### ISSUE TITLE
1473162392@qq.com

### ISSUE THREAD

**Issue by talway** [frankwei98/WHMCS_Alipay#1]
请问可以自动发货吗？

**Comment by frankwei98** [comment]
我这里WHMCS6.2可以啊 
不过建议你还是先测试一下 我用hostgator的WHMCS主机都无法判定已确认(开了确认收货后才开通的选项下 如果不勾该选项，一付款系统就判定为已支付 但客户还没真正确认收货）

元旦有空我看看能不能改一下这个 当然我也欢迎大家来贡献代码 毕竟我也是PHP初学者，能力有限

**Comment by talway** [comment]
自动发货    是否自动发货[需支持SSL]
支持SSL   你的服务器(PHP)是否支持SSL,如果工作不正常.就选择NO

这2个选项如何理解，是指https配置，还是php配置ssl就可以了；
我配置了https但自动发货，我测试无效；
你有测试买家付完款后，下一步这个接口可以去到支付宝进行发货动作吗？

**Comment by frankwei98** [comment]
这里的是否SSL应该是指服务器能不能正常访问SSL 你可以运行http://你的whmcs网站地址/modules/gateways/callback/alipaytest.php 测试HTTP和HTTPS到支付宝的连通性
