### ISSUE TITLE
WHMCS启用SSL访问后，自动发货等失效

### ISSUE THREAD

**Issue by tutugreen** [frankwei98/WHMCS_Alipay#2]
WHMCS 5.3.14
具体情况，使用HTTP方式访问财务系统，购买，付款，确认，一切正常。

如果在 后台>系统设置>常规设置>一般 中，添加了SSL访问方式，付款后无法正常发货，如启用“前台返回页面是否处理数据”，确认收货后无法到账。

如果在发起支付之前，设定系统URL为http的，再在跳转到付款页面之后（还未登陆付款时），设定为https的，在这之后付款。也可以正常完成自动发货等。。

Linode+Directadmin，支持SSL。

**Comment by tutugreen** [comment]
折腾了N次。
手动改了
    $alipay_config['return_url'] = "http://xxxxx.com/whmcs/modules/gateways/callback/alipay_return.php";
    $alipay_config['notify_url'] = "http://xxxxx.com/whmcs/modules/gateways/callback/alipay_callback.php";
解决了。
可能我主机问题吧~

**Comment by frankwei98** [comment]
感谢你的反馈  看起来我没有完全测试啊 :joy: 因为我直接把系统URL设置为https了 改天有空我去测试一下

**Comment by zlhdd108** [comment]
我也遇到了这个问题，无法自动发货；确认收货后也没办法入账，用的是WHMCS6，全站用了HTTPS
